"""
This module was autogenerated by gale.
"""

import pygame

from gale.game import Game
from gale.input_handler import InputData, InputHandler, InputListener

from src.Scene import Scene


class Tutorial(Game, InputListener):
    def init(self) -> None:
        self.scene = Scene()
        InputHandler.register_listener(self)

    def render(self, surface: pygame.Surface) -> None:
        self.scene.render(surface)

    def on_input(self, input_id: str, input_data: InputData) -> None:
        if input_id == "quit" and input_data.pressed:
            self.quit()
