embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"parrot\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/atlas/characters.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 2500.0\n"
  "friction: 1.0\n"
  "restitution: 0.1\n"
  "group: \"bird\"\n"
  "mask: \"destructible\"\n"
  "mask: \"ground\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 35.0395\n"
  "}\n"
  "linear_damping: 0.1\n"
  "angular_damping: 0.7\n"
  ""
}
