"""
This module was autogenerated by gale.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

from src import scene_loader

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, "quit")

# Size we want to emulate
VIRTUAL_WIDTH = 400
VIRTUAL_HEIGHT = 192

# Size of our actual window
WINDOW_WIDTH = VIRTUAL_WIDTH * 4
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 4

BASE_DIR = pathlib.Path(__file__).parent

TEXTURES = {
    "tiles": pygame.image.load(BASE_DIR / "assets" / "graphics" / "tileset.png"),
    "creatures": pygame.image.load(BASE_DIR / "assets" / "graphics" / "creatures.png"),
}

FRAMES = {
    "tiles": frames.generate_frames(TEXTURES["tiles"], 16, 16),
    "creatures": frames.generate_frames(TEXTURES["creatures"], 16, 16),
}

SceneLoader = scene_loader.YamlSceneLoader


def build_scene_path(scene_number: int) -> pathlib.Path:
    return BASE_DIR / "assets" / "scenes" / f"{scene_number:02}"
