"""
This module was autogenerated by gale.
"""
import settings
from src.spritesheets import Spritesheets

if __name__ == '__main__':
    game = Spritesheets(
        "Spritesheets",
        settings.WINDOW_WIDTH, settings.WINDOW_HEIGHT,
        settings.VIRTUAL_WIDTH, settings.VIRTUAL_HEIGHT
    )
    game.exec()
