"""
This module was autogenerated by gale.
"""

import settings
from src.Tutorial import Tutorial

if __name__ == "__main__":
    game = Tutorial(
        "Tutorial",
        settings.WINDOW_WIDTH,
        settings.WINDOW_HEIGHT,
        settings.VIRTUAL_WIDTH,
        settings.VIRTUAL_HEIGHT,
    )
    game.exec()
