"""
This module was autogenerated by gale.
"""
import pygame

from gale.game import Game
from gale.input_handler import InputData

import settings


class Spritesheets(Game):
    def init(self) -> None:
        w = 32
        h = 16

        self.texture = settings.TEXTURES['breakout']

        self.frames = []
        for i in range(0, 3):
            for j in range(0, 6):
                self.frames.append(pygame.Rect(w * j, h * i, w, h))

        self.current_frame = 0
        self.timer = 0

    def update(self, dt: float) -> None:
        self.timer += dt
        if self.timer >= 1:
            self.timer = 0
            self.current_frame = (self.current_frame + 1) % 18

    def render(self, surface: pygame.Surface) -> None:
        surface.blit(self.texture, (10, 10), self.frames[self.current_frame])

    def on_input(self, input_id: str, input_data: InputData) -> None:
        if (input_id == 'quit' and input_data.pressed):
            self.quit()
